@startuml
class UniTaskAsyncEnumerable <<static>> <<partial>> {
    + {static} TakeLast(source:IUniTaskAsyncEnumerable<TSource>, count:Int32) : IUniTaskAsyncEnumerable<TSource>
}
class "TakeLast`1"<TSource> <<sealed>> {
    + TakeLast(source:IUniTaskAsyncEnumerable<TSource>, count:int)
    + GetAsyncEnumerator(cancellationToken:CancellationToken) : IUniTaskAsyncEnumerator<TSource>
}
class "IUniTaskAsyncEnumerable`1"<T> {
}
class _TakeLast <<sealed>> {
    + _TakeLast(source:IUniTaskAsyncEnumerable<TSource>, count:int, cancellationToken:CancellationToken)
    + MoveNextAsync() : UniTask<bool>
    + DisposeAsync() : UniTask
}
class "IUniTaskAsyncEnumerator`1"<T> {
}
"IUniTaskAsyncEnumerable`1" "<TSource>" <|-- "TakeLast`1"
"TakeLast`1" +-- _TakeLast
MoveNextSource <|-- _TakeLast
"IUniTaskAsyncEnumerator`1" "<TSource>" <|-- _TakeLast
_TakeLast --> "Current" TSource
@enduml
